//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class soccerContext : DbContext
{
    internal object colourOne;

    public soccerContext()
        : base("name=soccerContext")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Colour> Colours { get; set; }
    public virtual DbSet<Competition> Competitions { get; set; }
    public virtual DbSet<Country> Countries { get; set; }
    public virtual DbSet<Game> Games { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<Team> Teams { get; set; }
    public virtual DbSet<Town> Towns { get; set; }
}
